In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, chi2, f_classif

In [6]:
data = pd.read_csv(r'D:\Teks 2024\All_data_sets\breast-cancer_classificationorcluster.csv')

In [7]:
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [10]:
data.shape

(569, 32)

In [11]:
from sklearn.linear_model import LogisticRegression

In [12]:
from sklearn.model_selection import StratifiedKFold

In [14]:
del data['id']

In [32]:
y = df['diagnosis']
X = df.drop(columns = 'diagnosis')

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,stratify=y,random_state=20)

In [44]:
model = LogisticRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           B       0.63      1.00      0.77        72
           M       0.00      0.00      0.00        42

    accuracy                           0.63       114
   macro avg       0.32      0.50      0.39       114
weighted avg       0.40      0.63      0.49       114



C:\Users\sekpu\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sekpu\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sekpu\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [51]:
kbest = SelectKBest(score_func=f_classif, k=10) 
kbest.fit(x, y)
scores = pd.DataFrame(kbest.scores_,index=x.columns)

In [52]:
scores

0
id                         0.898150
radius_mean              646.981021
texture_mean             118.096059
perimeter_mean           697.235272
area_mean                573.060747
smoothness_mean           83.651123
compactness_mean         313.233079
concavity_mean           533.793126
concave points_mean      861.676020
symmetry_mean             69.527444
fractal_dimension_mean     0.093459
radius_se                268.840327
texture_se                 0.039095
perimeter_se             253.897392
area_se                  243.651586
smoothness_se              2.557968
compactness_se            53.247339
concavity_se              39.014482
concave points_se        113.262760
symmetry_se                0.024117
fractal_dimension_se       3.468275
radius_worst             860.781707
texture_worst            149.596905
perimeter_worst          897.944219
area_worst               661.600206
smoothness_worst         122.472880
compactness_worst        304.341063
concavity_worst          436.691939
concave points_worst     964.385393
symmetry_worst           118.860232
fractal_dimension_worst   66.443961

In [54]:
scores.sort_values(by=0,ascending=False)

0
concave points_worst     964.385393
perimeter_worst          897.944219
concave points_mean      861.676020
radius_worst             860.781707
perimeter_mean           697.235272
area_worst               661.600206
radius_mean              646.981021
area_mean                573.060747
concavity_mean           533.793126
concavity_worst          436.691939
compactness_mean         313.233079
compactness_worst        304.341063
radius_se                268.840327
perimeter_se             253.897392
area_se                  243.651586
texture_worst            149.596905
smoothness_worst         122.472880
symmetry_worst           118.860232
texture_mean             118.096059
concave points_se        113.262760
smoothness_mean           83.651123
symmetry_mean             69.527444
fractal_dimension_worst   66.443961
compactness_se            53.247339
concavity_se              39.014482
fractal_dimension_se       3.468275
smoothness_se              2.557968
id                         0.898150
fractal_dimension_mean     0.093459
texture_se                 0.039095
symmetry_se                0.024117

CHI SQUARE TEST

In [66]:
from sklearn.feature_selection import SelectKBest, chi2
kbest = SelectKBest(chi2, k='all') 
kbest.fit_transform(x, y)

array([[8.4230200e+05, 1.7990000e+01, 1.0380000e+01, ..., 2.6540000e-01,
        4.6010000e-01, 1.1890000e-01],
       [8.4251700e+05, 2.0570000e+01, 1.7770000e+01, ..., 1.8600000e-01,
        2.7500000e-01, 8.9020000e-02],
       [8.4300903e+07, 1.9690000e+01, 2.1250000e+01, ..., 2.4300000e-01,
        3.6130000e-01, 8.7580000e-02],
       ...,
       [9.2695400e+05, 1.6600000e+01, 2.8080000e+01, ..., 1.4180000e-01,
        2.2180000e-01, 7.8200000e-02],
       [9.2724100e+05, 2.0600000e+01, 2.9330000e+01, ..., 2.6500000e-01,
        4.0870000e-01, 1.2400000e-01],
       [9.2751000e+04, 7.7600000e+00, 2.4540000e+01, ..., 0.0000000e+00,
        2.8710000e-01, 7.0390000e-02]])

In [67]:
kbest.scores_

array([4.62294838e+08, 2.66104917e+02, 9.38975081e+01, 2.01110286e+03,
       5.39916559e+04, 1.49899264e-01, 5.40307549e+00, 1.97123536e+01,
       1.05440354e+01, 2.57379775e-01, 7.43065536e-05, 3.46752472e+01,
       9.79353970e-03, 2.50571896e+02, 8.75850471e+03, 3.26620664e-03,
       6.13785332e-01, 1.04471761e+00, 3.05231563e-01, 8.03633831e-05,
       6.37136566e-03, 4.91689157e+02, 1.74449400e+02, 3.66503542e+03,
       1.12598432e+05, 3.97365694e-01, 1.93149220e+01, 3.95169151e+01,
       1.34854195e+01, 1.29886140e+00, 2.31522407e-01])

In [69]:
X = data[['perimeter_mean', 'area_mean', 'area_se', 'radius_worst', 'perimeter_worst', 'area_worst']]

In [70]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,stratify=y,random_state=20)

In [71]:
model = LogisticRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           B       0.95      0.97      0.96        72
           M       0.95      0.90      0.93        42

    accuracy                           0.95       114
   macro avg       0.95      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114



C:\Users\sekpu\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [90]:
k6best = SelectKBest(chi2, k=6)
k6best.fit(x, y)

k6best.get_support()

array([ True,  True,  True,  True,  True,  True])

In [91]:
x.columns[k6best.get_support()]

Index(['perimeter_mean', 'area_mean', 'area_se', 'radius_worst',
       'perimeter_worst', 'area_worst'],
      dtype='object')

In [80]:
X = data[['perimeter_mean', 'area_mean', 'area_se', 'radius_worst', 'perimeter_worst', 'area_worst']]

In [81]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,stratify=y,random_state=20)

In [82]:
model = LogisticRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           B       0.95      0.97      0.96        72
           M       0.95      0.90      0.93        42

    accuracy                           0.95       114
   macro avg       0.95      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114



C:\Users\sekpu\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [83]:
import warnings
warnings.filterwarnings('ignore')

In [86]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(estimator = LogisticRegression(),X=x,y=y,cv=StratifiedKFold(8))
print(scores.mean())

0.9332208528951487


In [87]:
kf6best = SelectKBest(f_classif,k=6)
kf6best.fit_transform(x,y)

array([[ 122.8  , 1001.   ,  153.4  ,   25.38 ,  184.6  , 2019.   ],
       [ 132.9  , 1326.   ,   74.08 ,   24.99 ,  158.8  , 1956.   ],
       [ 130.   , 1203.   ,   94.03 ,   23.57 ,  152.5  , 1709.   ],
       ...,
       [ 108.3  ,  858.1  ,   48.55 ,   18.98 ,  126.7  , 1124.   ],
       [ 140.1  , 1265.   ,   86.22 ,   25.74 ,  184.6  , 1821.   ],
       [  47.92 ,  181.   ,   19.15 ,    9.456,   59.16 ,  268.6  ]])

In [92]:
x.columns[kf6best.get_support()]

Index(['perimeter_mean', 'area_mean', 'area_se', 'radius_worst',
       'perimeter_worst', 'area_worst'],
      dtype='object')

In [94]:
xf = data[['perimeter_mean', 'area_mean', 'area_se', 'radius_worst', 'perimeter_worst', 'area_worst']]

In [95]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,stratify=y,random_state=20)

In [96]:
model = LogisticRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           B       0.95      0.97      0.96        72
           M       0.95      0.90      0.93        42

    accuracy                           0.95       114
   macro avg       0.95      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114



In [98]:
xf.columns

Index(['perimeter_mean', 'area_mean', 'area_se', 'radius_worst',
       'perimeter_worst', 'area_worst'],
      dtype='object')